version: "3"
services:
  user:
    build:
        context: .
        dockerfile: ./user/Dockerfile
    volumes:
      - "./db:/app/db" 
    ports:
      - "81:80"
      
  wallet:
    build:
        context: .
        dockerfile: ./wallet/Dockerfile
    volumes:
      - "./db:/app/db" 
    ports:
      - "82:80"
      
  payment:
    build:
        context: .
        dockerfile: ./payment/Dockerfile
    volumes:
      - "./db:/app/db" 
    ports:
      - "83:80"