version: "3"
services:
  api.user:
    build:
        context: .
        dockerfile: ./user/Dockerfile
    volumes:
      - "./db:/app/db" 
    ports:
      - "81:80"
      
  api.wallet:
    build:
        context: .
        dockerfile: ./wallet/Dockerfile
    volumes:
      - "./db:/app/db" 
    ports:
      - "82:80"
      
  api.payment:
    build:
        context: .
        dockerfile: ./payment/Dockerfile
    volumes:
      - "./db:/app/db" 
    ports:
      - "83:80"

  api.currency:
    build:
        context: .
        dockerfile: ./currency/Dockerfile
    volumes:
      - "./db:/app/db" 
    ports:
      - "84:80"

  payment.system.custompay.worker:
    build:
        context: .
        dockerfile: ./payment.system.custompay.worker/Dockerfile