version: '3.8'
services:
  rabbitMQ:
    image: "rabbitmq:3.9-management"
    environment:
      - RABBITMQ_DEFAULT_USER=peabody28
      - RABBITMQ_DEFAULT_PASS=1234
    volumes:
      - ./rabbitmq-config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq-config/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"

  rabbitMQ-dev:
    image: "rabbitmq:3.9-management"
    environment:
      - RABBITMQ_DEFAULT_USER=peabody28
      - RABBITMQ_DEFAULT_PASS=1234
    volumes:
      - ./rabbitmq-config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq-config/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5673:5672"
      - "15673:15672"